version: "3.9"

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=call_billing
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_HOST=%
    volumes:
      - /opt/mysqldata:/var/lib/mysql

  django:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    entrypoint: docker/web_entrypoint.sh
    environment:
      - DB_NAME=call_billing
      - DB_USERNAME=dev
      - DB_PASSWORD=secret
      - DB_PORT=3306
      - DB_HOST=db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure

